function(signal_studio_enable_warnings target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /permissive- /EHsc /Zc:__cplusplus)
    target_compile_options(${target} PUBLIC "$<$<COMPILE_LANGUAGE:CXX>:/utf-8>")
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion)
  endif()
endfunction()

function(signal_studio_verify_dependency_graph)
  set(_expected_SignalStudioCore "")
  set(_expected_SignalStudioCompute "SignalStudio::Core")
  set(_expected_SignalStudioData "SignalStudio::Core")
  set(_expected_SignalStudioTaskRuntime "SignalStudio::Compute;SignalStudio::Core")
  set(_expected_SignalStudioDSP "SignalStudio::Data;SignalStudio::Compute;SignalStudio::Core")
  set(_expected_SignalStudioVisualization "SignalStudio::Data;SignalStudio::TaskRuntime;SignalStudio::Core")
  set(_expected_SignalStudioModelRuntime "SignalStudio::Data;SignalStudio::Compute;SignalStudio::TaskRuntime;SignalStudio::Core")
  set(_expected_SignalStudioDataset "SignalStudio::Data;SignalStudio::TaskRuntime;SignalStudio::Core")
  set(_expected_SignalStudioPluginSDK "SignalStudio::Data;SignalStudio::TaskRuntime;SignalStudio::Core")
  set(_expected_SignalStudioWorkbench "SignalStudio::Visualization;SignalStudio::TaskRuntime;SignalStudio::Core")
  set(_modules
    SignalStudioCore SignalStudioCompute SignalStudioData SignalStudioTaskRuntime SignalStudioDSP
    SignalStudioModelRuntime SignalStudioDataset SignalStudioPluginSDK
  )
  if(TARGET SignalStudioVisualization)
    list(APPEND _modules SignalStudioVisualization SignalStudioWorkbench)
  endif()
  foreach(_module IN LISTS _modules)
    get_target_property(_interface ${_module} INTERFACE_LINK_LIBRARIES)
    if(NOT _interface)
      set(_interface "")
    endif()
    list(FILTER _interface EXCLUDE REGEX "^\\$<LINK_ONLY:")
    if(NOT "${_interface}" STREQUAL "${_expected_${_module}}")
      message(FATAL_ERROR "Approved dependency DAG mismatch for ${_module}: '${_interface}'")
    endif()
  endforeach()
endfunction()
