# Included by deploy_runtime.cmake after Qt deployment. The selected VS
# installation comes from CMake's generator rather than a repository-local path.
if(NOT DEFINED SS_VS_INSTALLATION_PATH OR NOT IS_DIRECTORY "${SS_VS_INSTALLATION_PATH}/VC")
    message(FATAL_ERROR "MSVC deployment requires the selected Visual Studio installation path")
endif()

set(redist_root "${SS_VS_INSTALLATION_PATH}/VC/Redist/MSVC")
file(GLOB redist_entries LIST_DIRECTORIES TRUE "${redist_root}/*")
set(versioned_redist_dirs "")
foreach(entry IN LISTS redist_entries)
    get_filename_component(version_name "${entry}" NAME)
    if(IS_DIRECTORY "${entry}" AND version_name MATCHES "^[0-9]+(\\.[0-9]+)+$")
        list(APPEND versioned_redist_dirs "${entry}")
    endif()
endforeach()
list(SORT versioned_redist_dirs COMPARE NATURAL ORDER DESCENDING)

if(SS_CONFIGURATION STREQUAL "Debug")
    set(crt_relative_pattern "debug_nonredist/x64/Microsoft.VC*.DebugCRT")
    set(required_crt_names msvcp140d.dll vcruntime140d.dll vcruntime140_1d.dll)
else()
    set(crt_relative_pattern "x64/Microsoft.VC*.CRT")
    set(required_crt_names msvcp140.dll vcruntime140.dll vcruntime140_1.dll)
endif()

set(selected_crt_dir "")
foreach(version_dir IN LISTS versioned_redist_dirs)
    file(GLOB crt_dirs LIST_DIRECTORIES TRUE "${version_dir}/${crt_relative_pattern}")
    list(SORT crt_dirs COMPARE NATURAL ORDER DESCENDING)
    foreach(crt_dir IN LISTS crt_dirs)
        set(has_required_crt TRUE)
        foreach(required_name IN LISTS required_crt_names)
            if(NOT EXISTS "${crt_dir}/${required_name}")
                set(has_required_crt FALSE)
            endif()
        endforeach()
        if(has_required_crt)
            set(selected_crt_dir "${crt_dir}")
            break()
        endif()
    endforeach()
    if(selected_crt_dir)
        break()
    endif()
endforeach()
if(NOT selected_crt_dir)
    message(FATAL_ERROR "No complete x64 ${SS_CONFIGURATION} MSVC CRT found under ${redist_root}")
endif()

file(GLOB crt_dlls LIST_DIRECTORIES FALSE "${selected_crt_dir}/*.dll")
foreach(runtime_file IN LISTS crt_dlls)
    get_filename_component(runtime_name "${runtime_file}" NAME)
    file(COPY_FILE "${runtime_file}" "${output_dir}/${runtime_name}" ONLY_IF_DIFFERENT)
endforeach()

set(ucrt_source "")
if(SS_CONFIGURATION STREQUAL "Debug")
    # The debug UCRT is shipped in the Windows SDK bin tree, and is not an OS
    # redistributable installed on a clean developer/test machine.
    if(IS_DIRECTORY "$ENV{WindowsSdkDir}")
        set(windows_sdk_root "$ENV{WindowsSdkDir}")
    else()
        cmake_host_system_information(RESULT windows_sdk_root
            QUERY WINDOWS_REGISTRY "HKLM/SOFTWARE/Microsoft/Windows Kits/Installed Roots"
            VALUE KitsRoot10 VIEW 64 ERROR_VARIABLE windows_sdk_error)
    endif()
    if(NOT IS_DIRECTORY "${windows_sdk_root}")
        message(FATAL_ERROR "Cannot locate the Windows SDK for debug UCRT deployment")
    endif()
    file(GLOB debug_ucrt_candidates LIST_DIRECTORIES FALSE
        "${windows_sdk_root}/bin/*/x64/ucrt/ucrtbased.dll"
        "${windows_sdk_root}/Redist/*/ucrt/DLLs/x64/ucrtbased.dll"
        "${windows_sdk_root}/Redist/ucrt/DLLs/x64/ucrtbased.dll")
    list(SORT debug_ucrt_candidates COMPARE NATURAL ORDER DESCENDING)
    if(NOT debug_ucrt_candidates)
        message(FATAL_ERROR "No x64 ucrtbased.dll found in the Windows SDK")
    endif()
    list(GET debug_ucrt_candidates 0 ucrt_source)
    file(COPY_FILE "${ucrt_source}" "${output_dir}/ucrtbased.dll" ONLY_IF_DIFFERENT)
endif()

foreach(required_name IN LISTS required_crt_names)
    if(NOT EXISTS "${output_dir}/${required_name}")
        message(FATAL_ERROR "Compiler runtime was not staged: ${required_name}")
    endif()
endforeach()
list(LENGTH crt_dlls crt_dll_count)
message(STATUS "Staged ${crt_dll_count} x64 ${SS_CONFIGURATION} CRT DLLs from ${selected_crt_dir}")
if(ucrt_source)
    message(STATUS "Staged debug UCRT from ${ucrt_source}")
endif()
