#include "ui/import/signal_import_dialog.h"
#include "ui/brand/brand_assets.h"
#include "ui/import/source_preview_widget.h"
#include "ui/controls/adaptive_value_edit.h"
#include "ui/controls/unsigned_value_edit.h"
#include "infrastructure/source_metadata.h"
#include "infrastructure/raw_sample_reader.h"
#include "ui/checkbox_style.h"
#include <QCheckBox>
#include <QComboBox>
#include <QDialogButtonBox>
#include <QFileDialog>
#include <QFileInfo>
#include <QGridLayout>
#include <QLabel>
#include <QPushButton>
#include <QScrollArea>
#include <QStackedWidget>
#include <QSplitter>
#include <QTableWidget>
#include <QHeaderView>
#include <QProgressBar>
#include <QTimer>
#include <QSizeGrip>
#include <QDragEnterEvent>
#include <QMimeData>
#include <QUrl>
#include <QInputDialog>
#include <QMessageBox>
#include <QMenu>
#include <QMouseEvent>
#include <QWindow>
#include <QAction>
#include <QRegularExpressionValidator>
#include <numeric>

namespace signalstudio {
namespace {
QLabel* text(const QString& content,QWidget* parent=nullptr){auto* l=new QLabel(content,parent);l->setWordWrap(true);return l;}
QPushButton* button(const QString& content,const char* name,QWidget* parent=nullptr){auto* b=new QPushButton(content,parent);b->setObjectName(name);b->setMinimumHeight(33);b->setAutoDefault(false);b->setAccessibleName(content);return b;}
QComboBox* combo(const QStringList& items,const char* name){auto* c=new QComboBox;c->setObjectName(name);c->addItems(items);c->setMinimumHeight(35);c->setMinimumWidth(0);c->setSizeAdjustPolicy(QComboBox::AdjustToMinimumContentsLengthWithIcon);c->setMinimumContentsLength(8);return c;}
QWidget* field(QGridLayout* grid,int row,int column,const QString& title,QWidget* control,QLabel** label=nullptr){auto* w=new QWidget;auto* v=new QVBoxLayout(w);v->setContentsMargins(0,0,0,0);v->setSpacing(6);auto* l=text(title);l->setStyleSheet("color:#a8c2d5;font-size:11px;");l->setBuddy(control);v->addWidget(l);v->addWidget(control);grid->addWidget(w,row,column);if(label)*label=l;control->setAccessibleName(title);return w;}
QWidget* divider(){auto* w=new QWidget;w->setFixedHeight(1);w->setStyleSheet("background:#30465c;");return w;}
QLineEdit* integerEdit(const char* name,const QString& value){auto* e=new UnsignedValueEdit(value.toULongLong());e->setObjectName(name);e->setMinimumHeight(35);return e;}
QString statusText(const ImportRow& r){switch(r.status){case ImportStatus::Reading:return "读入中";case ImportStatus::Ready:return "就绪";case ImportStatus::Partial:return "已保留前缀";case ImportStatus::Failed:return "失败："+r.error;case ImportStatus::Cancelled:return "已取消";default:return r.confirmed?(r.error.isEmpty()?"参数已确认":"需修正："+r.error):"需确认";}}
QString bytesText(std::uint64_t b){if(b>=1000000000)return QString::number(b/1e9,'f',2)+" GB";if(b>=1000000)return QString::number(b/1e6,'f',1)+" MB";if(b>=1000)return QString::number(b/1e3,'f',1)+" KB";return QString::number(b)+" B";}
}
SignalImportDialog::SignalImportDialog(const QString& projectName,QWidget* parent,QSettings* templateSettings):QDialog(parent),
    templateSettings_(QSettings::defaultFormat(),QSettings::UserScope,
        QCoreApplication::organizationName().isEmpty()?"Signal Studio":QCoreApplication::organizationName(),
        QCoreApplication::applicationName().isEmpty()?"SignalStudio":QCoreApplication::applicationName()),
    templates_(templateSettings?*templateSettings:templateSettings_){
    setWindowIcon(BrandAssets::windowIcon());
    setObjectName("signalImportDialog");setWindowTitle("导入信号数据 / Signal Import");setWindowFlags(Qt::Dialog|Qt::FramelessWindowHint);setModal(true);setSizeGripEnabled(true);setMinimumSize(900,650);resize(1210,860);setAcceptDrops(true);
    setStyleSheet("QDialog#signalImportDialog{background:#0d1a2c;border:1px solid #3a5269;border-radius:13px;color:#d8e8f4;} QLabel{color:#a8c2d5;font-size:12px;background:transparent;} QPushButton{background:#183049;color:#bad2e4;border:1px solid #3a5770;border-radius:7px;padding:0 13px;font-size:12px;} QPushButton:hover{background:#254562;} QPushButton:disabled{color:#65829d;border-color:#2a4159;} QPushButton[primary=true]{background:#197397;border-color:#39add0;color:#f4fdff;font-weight:600;} QLineEdit,QComboBox{background:#172d46;color:#e1f1fb;border:1px solid #36526d;border-radius:6px;padding:6px 10px;min-height:21px;font-size:12px;} QLineEdit:focus,QComboBox:focus{border-color:#53bddd;} QComboBox QAbstractItemView{background:#172d46;color:#e1f1fb;selection-background-color:#24617e;} QScrollArea{border:0;background:#0d1a2c;} QTableWidget{background:#102135;color:#bed8eb;border:0;gridline-color:#2a4159;} QHeaderView::section{background:#193149;color:#9ec0d8;border:0;border-bottom:1px solid #36526d;padding:10px;font-size:11px;} QCheckBox{color:#a6bdd2;font-size:11px;spacing:8px;}"+checkboxStyleSheet());
    auto* root=new QVBoxLayout(this);root->setContentsMargins(1,1,1,1);root->setSpacing(0);
    auto* header=new QWidget;header->setFixedHeight(73);header->setStyleSheet("background:#15263b;");auto* h=new QHBoxLayout(header);h->setContentsMargins(26,10,26,10);auto* titles=new QVBoxLayout;titles->setSpacing(5);
    auto* heading=text("导入信号数据 <span style='color:#83a7be;font-size:13px;font-weight:400'>/ Signal Import</span>");heading->setStyleSheet("font-size:19px;font-weight:600;color:#d8e8f4;");titles->addWidget(heading);auto* subtitle=text("选择采样文件、分别确认采样结构与分量编码，然后创建分析数据源");subtitle->setStyleSheet("font-size:11px;color:#829eb5;");titles->addWidget(subtitle);h->addLayout(titles,1);h->addWidget(text("A1.2"));auto* close=button("×","importClose");close->setFixedWidth(33);close->setToolTip("关闭");h->addWidget(close);connect(close,&QPushButton::clicked,this,&SignalImportDialog::reject);root->addWidget(header);
    auto* nav=new QWidget;nav->setFixedHeight(48);nav->setStyleSheet("background:#102135;");auto* n=new QHBoxLayout(nav);n->setContentsMargins(22,0,22,0);n->setSpacing(2);
    int tab=0;for(const auto& name:QStringList{"快速导入","批量导入","格式模板"}){auto* b=button(name,qPrintable(QString("importTab%1").arg(tab)));b->setFixedHeight(48);b->setCheckable(true);b->setStyleSheet("QPushButton{border:0;border-bottom:2px solid transparent;background:transparent;color:#8da7bd;padding:0 19px;border-radius:0;}QPushButton:checked{color:#70d7f3;border-bottom-color:#46c6eb;}");n->addWidget(b);tabs_.append(b);connect(b,&QPushButton::clicked,this,[this,i=tab]{setPage(i);});++tab;}n->addStretch();n->addWidget(text("当前工程 · "+projectName));root->addWidget(nav);
    pages_=new QStackedWidget;pages_->setObjectName("importPages");root->addWidget(pages_,1);for(int i=0;i<3;++i)pages_->addWidget(new QWidget);buildSingle(pages_->widget(0));buildBatch(pages_->widget(1));buildTemplates(pages_->widget(2));
    auto* foot=new QWidget;foot->setFixedHeight(66);foot->setObjectName("importFooter");foot->setStyleSheet("background:#15283c;border-top:1px solid #2a4159;");auto* f=new QHBoxLayout(foot);f->setContentsMargins(22,10,22,10);footer_=text("请选择数据文件并确认解释参数");footer_->setObjectName("importFooterStatus");f->addWidget(footer_,1);auto* cancel=button("取消","importCancel");f->addWidget(cancel);import_=button("导入到工程 →","importStart");import_->setProperty("primary",true);f->addWidget(import_);auto* grip=new QSizeGrip(this);f->addWidget(grip);root->addWidget(foot);connect(cancel,&QPushButton::clicked,this,&SignalImportDialog::reject);connect(import_,&QPushButton::clicked,this,&SignalImportDialog::startImport);
    inputPolicy_=new ParameterInputPolicy(this);buildOverlay();timer_=new QTimer(this);timer_->setInterval(30);connect(timer_,&QTimer::timeout,this,&SignalImportDialog::pollImport);timer_->start();setPage(0);refreshSummary(false);
}
SignalImportDialog::~SignalImportDialog(){controller_.stopAll();}
void SignalImportDialog::buildSingle(QWidget* page){
auto* v=new QVBoxLayout(page);v->setContentsMargins(0,0,0,0);v->setSpacing(0);auto* source=new QWidget;source->setFixedHeight(83);source->setObjectName("importSourceStrip");source->setStyleSheet("QWidget#importSourceStrip{background:#122238;border-bottom:1px solid #293f55;}");auto* s=new QHBoxLayout(source);s->setContentsMargins(22,14,22,14);s->setSpacing(14);auto* icon=text("");icon->setPixmap(BrandAssets::pixmap("icon",QSize(32,32),devicePixelRatioF(),"primary"));icon->setObjectName("importSourceIcon");icon->setFixedSize(42,42);icon->setAlignment(Qt::AlignCenter);icon->setStyleSheet("background:#174861;border:1px solid #2a6685;border-radius:9px;color:#83dcf3;font-size:22px;");s->addWidget(icon);auto* core=new QVBoxLayout;filename_=text("未选择数据文件");filename_->setObjectName("importFilename");filename_->setStyleSheet("color:#e3f2fc;font-weight:600;font-size:13px;");details_=text("本地只读数据源");details_->setStyleSheet("color:#86a0b6;font-size:11px;");core->addWidget(filename_);core->addWidget(details_);s->addLayout(core,1);auto* choose=button("↗ 选择文件","chooseImportFile");s->addWidget(choose);connect(choose,&QPushButton::clicked,this,&SignalImportDialog::chooseFiles);v->addWidget(source);
    auto* split=new QSplitter(Qt::Horizontal);split->setHandleWidth(1);auto* formScroll=new QScrollArea;formScroll->setWidgetResizable(true);auto* form=new QWidget;form->setMinimumWidth(370);auto* left=new QVBoxLayout(form);left->setContentsMargins(22,17,22,25);left->setSpacing(13);formScroll->setWidget(form);split->addWidget(formScroll);
    auto* group=text("01　采样结构与数值编码");group->setStyleSheet("font-size:13px;font-weight:600;color:#cbe1f0;");left->addWidget(group);auto* grid=new QGridLayout;grid->setSpacing(12);grid->setColumnStretch(0,1);grid->setColumnStretch(1,1);
    structure_=combo({"复数 IQ（双分量）","实数 ADC（单分量）"},"importStructure");encoding_=combo({"Int16 · 16 位有符号整数","Float32 · 32 位浮点","Int8 · 8 位有符号整数","UInt8 · 8 位无符号整数","Int32 · 32 位有符号整数","Float64 · 64 位浮点"},"importEncoding");
    field(grid,0,0,"采样结构",structure_);field(grid,0,1,"分量数值编码",encoding_);
    order_=combo({"Little Endian（小端）","Big Endian（大端）"},"importByteOrder");layout_=combo({"IQ 交替 · I0,Q0,I1,Q1…","QI 交替 · Q0,I0,Q1,I1…","分量分块 · I 区块 / Q 区块"},"importIQLayout");orderField_=field(grid,1,0,"字节序",order_);layoutField_=field(grid,1,1,"I/Q 分量排列",layout_);left->addLayout(grid);
    auto* summaryPanel=new QWidget;summaryPanel->setObjectName("importSummaryPanel");summaryPanel->setMinimumHeight(111);summaryPanel->setStyleSheet("QWidget#importSummaryPanel{background:#153047;border:1px solid #37637f;border-left:3px solid #4cc9e8;border-radius:9px;}");auto* summaryLayout=new QVBoxLayout(summaryPanel);summaryLayout->setContentsMargins(14,12,14,12);summaryLayout->setSpacing(9);auto* summaryHead=new QHBoxLayout;summaryHead->addWidget(text("● 自动生成的完整数据格式"),1);formatCode_=text("CI16");formatCode_->setObjectName("importFormatCode");formatCode_->setAlignment(Qt::AlignCenter);formatCode_->setFixedSize(66,28);formatCode_->setStyleSheet("color:#77e4f6;font-size:14px;font-weight:600;background:#194962;border:1px solid #387997;border-radius:5px;");summaryHead->addWidget(formatCode_);summaryLayout->addLayout(summaryHead);summary_=text("");summary_->setObjectName("importFormatSummary");summary_->setStyleSheet("color:#d8ebf8;font-size:11px;");summaryLayout->addWidget(summary_);summaryLayout->addWidget(divider());formatSize_=text("");formatSize_->setStyleSheet("color:#8bb2ca;font-size:10px;");summaryLayout->addWidget(formatSize_);left->addWidget(summaryPanel);left->addWidget(divider());
    auto* acquisition=new QHBoxLayout;auto* title=text("02　采集参数");title->setStyleSheet("font-size:13px;font-weight:600;color:#cbe1f0;");acquisition->addWidget(title);provenance_=text("参数未确认");provenance_->setObjectName("importProvenance");provenance_->setStyleSheet("color:#82a1b8;font-size:10px;");acquisition->addWidget(provenance_,1);left->addLayout(acquisition);
    auto* inputs=new QGridLayout;inputs->setSpacing(12);inputs->setColumnStretch(0,1);inputs->setColumnStretch(1,1);fs_=new AdaptiveValueEdit(UnitKind::SampleRate,102.4e6);fs_->setObjectName("importSampleRate");fc_=new AdaptiveValueEdit(UnitKind::Frequency,830e6);fc_->setObjectName("importCenterFrequency");bw_=new AdaptiveValueEdit(UnitKind::Frequency,80e6);bw_->setObjectName("importBandwidth");start_=new AdaptiveValueEdit(UnitKind::Time,0);start_->setObjectName("importPreviewStart");field(inputs,0,0,"复采样率",fs_,&fsLabel_);field(inputs,0,1,"RF 中心频率",fc_,&fcLabel_);field(inputs,1,0,"有效显示带宽",bw_);field(inputs,1,1,"预览起始时间",start_);left->addLayout(inputs);
    auto* hint=text("AUTO　Hz / kHz / MHz / GHz · S/s / kS/s / MS/s / GS/s");hint->setStyleSheet("color:#82a9c2;background:#122a41;border:1px solid #294d67;border-radius:6px;padding:8px;font-size:11px;");left->addWidget(hint);
    stats_=text("");stats_->hide();auto* miniStats=new QHBoxLayout;miniStats->setSpacing(8);const QStringList statTitles{"每通道样本数","采集时长","RF 频段 · 自适应"};QLabel** values[]{&countStat_,&durationStat_,&frequencyStat_};for(int i=0;i<3;++i){auto* stat=new QWidget;stat->setObjectName("importMiniStat");stat->setStyleSheet("QWidget#importMiniStat{background:#162b41;border:1px solid #28465e;border-radius:7px;}");auto* box=new QVBoxLayout(stat);box->setContentsMargins(10,10,10,10);auto* value=text("—");value->setStyleSheet("font-size:12px;font-weight:600;color:#cbe1f0;");*values[i]=value;box->addWidget(value);auto* caption=text(statTitles[i]);caption->setStyleSheet("color:#7e9db4;font-size:10px;");box->addWidget(caption);miniStats->addWidget(stat,1);}left->addLayout(miniStats);
    auto* advancedToggle=button("▸ 高级格式设置（偏移、通道、校准）","importAdvancedToggle");advancedToggle->setCheckable(true);advancedToggle->setStyleSheet("border:0;background:transparent;color:#91cbe1;text-align:left;padding:0;");left->addWidget(advancedToggle);advanced_=new QWidget;advanced_->setObjectName("importAdvanced");advanced_->setStyleSheet("QWidget#importAdvanced{background:#102338;border:1px solid #2c4b63;border-radius:8px;}");auto* a=new QVBoxLayout(advanced_);auto* g=new QGridLayout;g->setSpacing(12);header_=integerEdit("importHeaderBytes","0");trailer_=integerEdit("importTrailerBytes","0");channels_=integerEdit("importChannels","1");channel_=combo({"CH 0"},"importSelectedChannel");channelLayout_=combo({"按时刻交织（CH0, CH1…）","按通道分块（CH0 全部, CH1 全部…）"},"importChannelLayout");field(g,0,0,"文件头偏移（字节）",header_);field(g,0,1,"文件尾忽略（字节）",trailer_);field(g,1,0,"接收通道数",channels_);field(g,1,1,"预览通道",channel_);auto* row=new QWidget;auto* rowLayout=new QGridLayout(row);rowLayout->setContentsMargins(0,0,0,0);field(rowLayout,0,0,"多通道存储",channelLayout_);g->addWidget(row,2,0,1,2);a->addLayout(g);normalize_=new QCheckBox("将整数 ADC 样本归一化到 [-1, 1) 进行分析");normalize_->setObjectName("importNormalize");normalize_->setChecked(true);a->addWidget(normalize_);advanced_->hide();left->addWidget(advanced_);connect(advancedToggle,&QPushButton::toggled,advanced_,&QWidget::setVisible);
    confirmed_=new QCheckBox("确认当前文件的采样格式及采集参数");confirmed_->setObjectName("importConfirmFormat");left->addWidget(confirmed_);validation_=text("未找到元数据时需要人工确认");validation_->setObjectName("importValidation");validation_->setStyleSheet("background:#163047;border:1px solid #27516b;border-radius:7px;padding:10px;color:#a6ccdf;font-size:11px;");left->addWidget(validation_);left->addStretch();
    auto* previewScroll=new QScrollArea;previewScroll->setWidgetResizable(true);previewScroll->setStyleSheet("background:#0e1b2e;border:0;");auto* previewBody=new QWidget;auto* pv=new QVBoxLayout(previewBody);pv->setContentsMargins(21,17,21,18);preview_=new SourcePreviewWidget;pv->addWidget(preview_);pv->addStretch();previewScroll->setWidget(previewBody);split->addWidget(previewScroll);split->setSizes({588,622});split->setStretchFactor(0,1);split->setStretchFactor(1,1);v->addWidget(split,1);
    for(auto* c:{structure_,encoding_,order_,layout_,channelLayout_,channel_})connect(c,&QComboBox::currentIndexChanged,this,[this]{commitConfiguration();});
    for(auto* c:{fs_,fc_,bw_})connect(c,&AdaptiveValueEdit::valueCommitted,this,[this]{commitConfiguration();});
    connect(start_,&AdaptiveValueEdit::valueCommitted,this,[this]{previewSample_.reset();refreshSummary();});
    start_->setContextMenuPolicy(Qt::CustomContextMenu);
    connect(start_,&QWidget::customContextMenuRequested,this,[this](const QPoint& point){
        QMenu menu(this);const QStringList titles{"文件起始","文件中间","文件尾部","指定样本位置"};
        for(int i=0;i<4;++i){auto* action=menu.addAction(titles[i]);action->setObjectName(QString("previewPosition%1").arg(i));connect(action,&QAction::triggered,this,[this,i]{
            if(controller_.running()||current_>=controller_.rows().size())return;const auto& metadata=controller_.rows()[current_].metadata;const auto count=metadata.sampleCount;if(!count)return;
            SampleIndex position=i==1?count/2:i==2?(count>16384?count-16384:0):0;
            if(i==3){bool accepted=false;const auto value=QInputDialog::getText(this,"指定预览样本","样本索引（从0开始）",QLineEdit::Normal,"0",&accepted);bool valid=false;position=value.toULongLong(&valid);if(!accepted)return;if(!valid||position>=count){validation_->setText("样本索引超出物理数据范围");return;}}
            previewSample_=position;start_->discard();start_->setValue(static_cast<double>(position)/metadata.sampleRateHz);refreshSummary();
        });}
        menu.exec(start_->mapToGlobal(point));
    });
    for(auto* e:{header_,trailer_,channels_})static_cast<UnsignedValueEdit*>(e)->applied=[this]{commitConfiguration();};
    static_cast<UnsignedValueEdit*>(channels_)->minimum=1;static_cast<UnsignedValueEdit*>(channels_)->maximum=128;
    connect(normalize_,&QCheckBox::toggled,this,[this]{commitConfiguration();});connect(confirmed_,&QCheckBox::toggled,this,[this]{commitConfiguration();});
    connect(preview_,&SourcePreviewWidget::previewFinished,this,[this]{updateProgress();});
}
void SignalImportDialog::buildBatch(QWidget* page){auto* v=new QVBoxLayout(page);v->setContentsMargins(22,18,22,18);v->setSpacing(14);auto* h=new QHBoxLayout;auto* title=text("<b>批量导入</b><br>分别校验多个文件，每个文件保留独立采集参数。");h->addWidget(title,1);auto* choose=button("＋ 选择本地文件","batchChooseFiles");h->addWidget(choose);connect(choose,&QPushButton::clicked,this,&SignalImportDialog::chooseFiles);v->addLayout(h);auto* drop=text("将 RAW 采样文件拖到此处，或选择本地文件添加");drop->setAlignment(Qt::AlignCenter);drop->setFixedHeight(56);drop->setStyleSheet("background:#112338;border:1px dashed #3a617b;border-radius:7px;color:#80acc6;");v->addWidget(drop);
    auto* body=new QHBoxLayout;table_=new QTableWidget(0,6);table_->setObjectName("importBatchTable");table_->setHorizontalHeaderLabels({"数据文件","大小","格式","采样率","校验结果",""});table_->verticalHeader()->hide();table_->setSelectionBehavior(QAbstractItemView::SelectRows);table_->setSelectionMode(QAbstractItemView::ExtendedSelection);table_->setEditTriggers(QAbstractItemView::NoEditTriggers);table_->horizontalHeader()->setSectionResizeMode(0,QHeaderView::Stretch);table_->horizontalHeader()->setSectionResizeMode(2,QHeaderView::ResizeToContents);table_->horizontalHeader()->setSectionResizeMode(4,QHeaderView::Stretch);table_->setColumnWidth(1,85);table_->setColumnWidth(3,110);table_->setColumnWidth(5,44);body->addWidget(table_,1);connect(table_,&QTableWidget::cellClicked,this,[this](int row,int){selectRow(row);});
    auto* side=new QWidget;side->setFixedWidth(310);auto* s=new QVBoxLayout(side);s->setContentsMargins(16,0,0,0);s->setSpacing(13);s->addWidget(text("<b>批量格式设置</b>"));s->addWidget(text("将模板应用到所有选中项"));templateChoice_=combo({"通用 CI16 · IQ · LE","通用 CF32 · IQ · LE","通用 CI8 · IQ","通用 CU8 · IQ","实数 Int16 ADC"},"importBatchTemplate");s->addWidget(templateChoice_);auto* apply=button("应用结构与编码设置","batchApplyTemplate");s->addWidget(apply);connect(apply,&QPushButton::clicked,this,[this]{applyTemplate(templateChoice_->currentIndex(),true);});s->addWidget(divider());s->addWidget(text("<b>当前文件</b>"));batchSelected_=text("暂无文件");batchSelected_->setObjectName("batchSelectedDetails");s->addWidget(batchSelected_);auto* edit=button("进入单文件参数编辑 →","batchEditSelected");s->addWidget(edit);connect(edit,&QPushButton::clicked,this,[this]{setPage(0);});auto* retry=button("重试当前文件","batchRetrySelected");s->addWidget(retry);connect(retry,&QPushButton::clicked,this,[this]{if(!controller_.running()&&current_<controller_.rows().size()){controller_.rows()[current_].status=ImportStatus::Pending;previewAfterLoad_=false;controller_.start({current_});overlay_->show();}});auto* cancel=button("取消当前文件","batchCancelSelected");s->addWidget(cancel);connect(cancel,&QPushButton::clicked,this,[this]{controller_.stopRow(current_);});s->addStretch();body->addWidget(side);v->addLayout(body,1);auto* actions=new QHBoxLayout;actions->addStretch();auto* clear=button("清空列表","batchClear");actions->addWidget(clear);connect(clear,&QPushButton::clicked,this,[this]{if(controller_.running())return;controller_.rows().clear();preview_->clear();loadCurrent();refreshBatch();});auto* start=button("开始批量导入 →","batchImport");start->setProperty("primary",true);actions->addWidget(start);connect(start,&QPushButton::clicked,this,&SignalImportDialog::startImport);v->addLayout(actions);
}
void SignalImportDialog::buildTemplates(QWidget* page){
    auto* v=new QVBoxLayout(page);v->setContentsMargins(0,0,0,0);v->setSpacing(0);
    auto* head=new QWidget;auto* h=new QHBoxLayout(head);h->setContentsMargins(23,20,23,18);
    h->addWidget(text("<b>格式模板</b><br>保存采样结构、分量编码、字节序和布局，一键填充导入参数。"),1);
    auto* import=button("导入模板 JSON","importTemplateJson");h->addWidget(import);
    auto* exportButton=button("↓ 导出当前配置 JSON","exportConfig");h->addWidget(exportButton);v->addWidget(head);
    connect(import,&QPushButton::clicked,this,[this]{const auto path=QFileDialog::getOpenFileName(this,"导入原生格式模板",{},"JSON (*.json)");QString error;if(!path.isEmpty()&&!importTemplates(path,error))QMessageBox::warning(this,"模板未导入",error);});
    connect(exportButton,&QPushButton::clicked,this,[this]{const auto path=QFileDialog::getSaveFileName(this,"导出原生格式模板","signal-import-templates.json","JSON (*.json)");if(path.isEmpty())return;QString error;if(current_<controller_.rows().size()&&!saveTemplate("当前解释参数",error)){QMessageBox::warning(this,"导出失败",error);return;}if(!exportTemplates(path,error))QMessageBox::warning(this,"导出失败",error);});
    auto* scroll=new QScrollArea;scroll->setWidgetResizable(true);auto* body=new QWidget;templateGridHost_=new QVBoxLayout(body);templateGridHost_->setContentsMargins(23,18,23,18);scroll->setWidget(body);v->addWidget(scroll,1);
    auto* saveRow=new QWidget;auto* saveLayout=new QHBoxLayout(saveRow);saveLayout->setContentsMargins(23,18,23,20);saveLayout->addWidget(text("<b>保存当前解释参数为模板</b><br>用户模板独立保存；应用格式时保留各源 Fs/Fc。"),1);
    auto* save=button("＋ 新建模板","saveTemplate");save->setProperty("primary",true);saveLayout->addWidget(save);v->addWidget(saveRow);
    connect(save,&QPushButton::clicked,this,[this]{bool ok=false;const auto name=QInputDialog::getText(this,"新建格式模板","模板名称",QLineEdit::Normal,"我的采样格式",&ok);QString error;if(ok&&!saveTemplate(name,error))QMessageBox::warning(this,"模板未保存",error);});refreshTemplates();
}
void SignalImportDialog::refreshTemplates(){
    while(auto* item=templateGridHost_->takeAt(0)){delete item->widget();delete item;}
    auto* gridWidget=new QWidget;auto* grid=new QGridLayout(gridWidget);grid->setContentsMargins(0,0,0,0);grid->setSpacing(12);
    const auto& list=templates_.templates();for(int i=0;i<static_cast<int>(list.size());++i){
        const auto& t=list[i];auto* card=button("",qPrintable(QString("importTemplate%1").arg(i)));card->setMinimumHeight(153);card->setStyleSheet("QPushButton{text-align:left;background:#162b41;border:1px solid #35546c;border-radius:8px;} QLabel{border:0;background:transparent;padding:0;}");
        auto* box=new QVBoxLayout(card);box->setContentsMargins(17,14,17,14);auto* glyph=text("▧");glyph->setStyleSheet("font-size:24px;color:#62d3f0;");box->addWidget(glyph);
        auto* name=text(t.name);name->setStyleSheet("font-size:13px;font-weight:600;color:#d8e8f4;");box->addWidget(name);
        const auto& f=t.format;box->addWidget(text(QString::fromStdString(formatId(f))+" · "+(f.byteOrder==ByteOrder::Big?"Big Endian":f.byteOrder==ByteOrder::Little?"Little Endian":"字节序无关")+" · "+QString::number(f.channels)+" Channel"));
        box->addWidget(text(t.builtin?"点击应用到当前文件 → 内置":"点击应用到当前文件 → 自定义"));
        for(auto* child:card->findChildren<QLabel*>())child->setAttribute(Qt::WA_TransparentForMouseEvents);
        grid->addWidget(card,i/3,i%3);connect(card,&QPushButton::clicked,this,[this,i]{applyTemplate(i);setPage(0);});
    }
    templateGridHost_->addWidget(gridWidget);QStringList names;for(const auto& id:templates_.recent())for(const auto& t:list)if(t.id==id)names.append(t.name);
    recentTemplates_=text("最近模板："+names.join(" · "));recentTemplates_->setObjectName("importRecentTemplates");templateGridHost_->addWidget(recentTemplates_);templateGridHost_->addStretch();
    const QSignalBlocker blocker(templateChoice_);templateChoice_->clear();for(const auto& t:list)templateChoice_->addItem(t.name);
}
bool SignalImportDialog::saveTemplate(const QString& name,QString& error){if(current_>=controller_.rows().size()){error="没有当前文件参数";return false;}if(!templates_.add(name,controller_.rows()[current_].metadata.sampleFormat,error))return false;refreshTemplates();return true;}
bool SignalImportDialog::importTemplates(const QString& path,QString& error){if(!templates_.importFile(path,error))return false;refreshTemplates();return true;}
bool SignalImportDialog::exportTemplates(const QString& path,QString& error) const {
    for(const auto& row:controller_.rows())if(QFileInfo(path).absoluteFilePath()==QFileInfo(QString::fromStdString(row.metadata.path)).absoluteFilePath()){error="禁止覆盖原始样本文件";return false;}
    return templates_.exportFile(path,error);
}
void SignalImportDialog::chooseFiles(){const auto paths=QFileDialog::getOpenFileNames(this,"选择采样文件",{},"采样数据 (*.iq *.dat *.raw *.bin *.cf32 *.cu8 *.sigmf-data *.sigmf-meta);;所有文件 (*)");for(const auto& path:paths)addPath(path);}
bool SignalImportDialog::addPath(const QString& path){
    if(controller_.running())return false;const auto suggestions=suggestSourceMetadata(path);ImportRow row;row.metadata.path=suggestions.dataPath.toUtf8().toStdString();row.metadata.name=QFileInfo(suggestions.dataPath).fileName().toUtf8().toStdString();row.metadata.demo=false;row.metadata.sampleFormat=suggestions.format.value_or(SampleFormat{});row.metadata.sampleRateHz=suggestions.sampleRateHz.value_or(102.4e6);row.metadata.centerFrequencyHz=suggestions.centerFrequencyHz.value_or(0);row.metadata.declaredBandwidthHz=suggestions.bandwidthHz.value_or(0);row.acquisitionKnown=suggestions.sampleRateHz.has_value()&&suggestions.centerFrequencyHz.has_value();row.confirmed=suggestions.format.has_value()&&suggestions.sampleRateHz.has_value()&&suggestions.centerFrequencyHz.has_value();row.provenance=suggestions.provenance+" "+suggestions.conflicts+" "+suggestions.warnings.left(600);row.error=suggestions.error;row.metadataError=suggestions.error;
    QString error;if(!controller_.add(std::move(row),error)){validation_->setText(error);return false;}selectRow(static_cast<int>(controller_.rows().size()-1));refreshBatch();return true;
}
void SignalImportDialog::selectRow(int row){if(controller_.running()||row<0||static_cast<std::size_t>(row)>=controller_.rows().size())return;previewSample_.reset();inputPolicy_->setContext(QString::number(row));current_=static_cast<std::size_t>(row);loadCurrent();}
void SignalImportDialog::loadCurrent(){updating_=true;if(current_>=controller_.rows().size()){filename_->setText("未选择数据文件");details_->setText("本地只读数据源");confirmed_->setChecked(false);updating_=false;refreshSummary(false);return;}
    const auto& row=controller_.rows()[current_];const auto& m=row.metadata;const auto& f=m.sampleFormat;filename_->setText(QString::fromStdString(m.name));filename_->setToolTip(QString::fromStdString(m.path));details_->setText(bytesText(static_cast<std::uint64_t>(std::max<qint64>(0,QFileInfo(QString::fromStdString(m.path)).size())))+QString(" · 本地文件 · %1 通道").arg(f.channels));provenance_->setText(row.provenance);structure_->setCurrentIndex(f.structure==SampleStructure::Real?1:0);constexpr int encodingMap[]{2,3,0,4,1,5};encoding_->setCurrentIndex(encodingMap[static_cast<int>(f.componentEncoding)]);order_->setCurrentIndex(f.byteOrder==ByteOrder::Big?1:0);layout_->setCurrentIndex(f.iqLayout==IQLayout::QIInterleaved?1:f.iqLayout==IQLayout::PlanarIQ?2:0);if(f.byteOrder!=ByteOrder::NotApplicable)previousOrder_=f.byteOrder;if(f.iqLayout!=IQLayout::NotApplicable)previousLayout_=f.iqLayout;fs_->discard();fc_->discard();bw_->discard();fs_->setValue(m.sampleRateHz);fc_->setValue(m.centerFrequencyHz);bw_->setValue(m.declaredBandwidthHz);static_cast<UnsignedValueEdit*>(header_)->setValue(f.headerBytes);static_cast<UnsignedValueEdit*>(trailer_)->setValue(f.trailerBytes);static_cast<UnsignedValueEdit*>(channels_)->setValue(f.channels);channel_->clear();for(std::uint32_t c=0;c<f.channels;++c)channel_->addItem(QString("CH %1").arg(c));channel_->setCurrentIndex(static_cast<int>(f.selectedChannel));channelLayout_->setCurrentIndex(f.channelLayout==ChannelLayout::ChannelPlanar?1:0);normalize_->setChecked(f.normalizeIntegerAdc);confirmed_->setChecked(row.confirmed);updating_=false;refreshSummary();}
void SignalImportDialog::commitConfiguration(){if(updating_||controller_.running())return;
    constexpr ComponentEncoding encodings[]{ComponentEncoding::Int16,ComponentEncoding::Float32,ComponentEncoding::Int8,ComponentEncoding::UInt8,ComponentEncoding::Int32,ComponentEncoding::Float64};SampleFormat f;f.structure=structure_->currentIndex()?SampleStructure::Real:SampleStructure::ComplexIQ;f.componentEncoding=encodings[encoding_->currentIndex()];
    if(sender()==order_)previousOrder_=order_->currentIndex()?ByteOrder::Big:ByteOrder::Little;if(sender()==layout_)previousLayout_=static_cast<IQLayout>(layout_->currentIndex()+1);
    f.byteOrder=bytesPerComponent(f)==1?ByteOrder::NotApplicable:previousOrder_;f.iqLayout=f.structure==SampleStructure::Real?IQLayout::NotApplicable:previousLayout_;f.normalizeIntegerAdc=f.componentEncoding<ComponentEncoding::Float32&&normalize_->isChecked();
    bool okH=false,okT=false,okC=false;f.headerBytes=header_->text().toULongLong(&okH);f.trailerBytes=trailer_->text().toULongLong(&okT);const auto ch=channels_->text().toUInt(&okC);f.channels=ch;f.channelLayout=channelLayout_->currentIndex()?ChannelLayout::ChannelPlanar:ChannelLayout::TimeInterleaved;
    if(okC&&ch>=1&&ch<=128&&channel_->count()!=static_cast<int>(ch)){const QSignalBlocker block(channel_);const int selected=channel_->currentIndex();channel_->clear();for(std::uint32_t c=0;c<ch;++c)channel_->addItem(QString("CH %1").arg(c));channel_->setCurrentIndex(std::clamp(selected,0,static_cast<int>(ch)-1));}
    f.selectedChannel=static_cast<std::uint32_t>(std::max(0,channel_->currentIndex()));
    if(!okH||!okT||!okC){validation_->setText("偏移与通道必须为有效整数");import_->setEnabled(false);return;}
    if(current_<controller_.rows().size()){
        auto& row=controller_.rows()[current_];const bool changed=row.metadata.sampleFormat!=f||row.metadata.sampleRateHz!=fs_->value()||row.metadata.centerFrequencyHz!=fc_->value()||row.metadata.declaredBandwidthHz!=bw_->value()||row.confirmed!=confirmed_->isChecked();
        row.metadata.sampleFormat=f;row.metadata.sampleRateHz=fs_->value();row.metadata.centerFrequencyHz=fc_->value();row.metadata.declaredBandwidthHz=bw_->value();row.confirmed=confirmed_->isChecked();
        if(changed){row.status=ImportStatus::Pending;row.load={};row.committed=false;if(!row.provenance.contains("已手动覆盖"))row.provenance+=" · 已手动覆盖";}
    }
    refreshSummary();refreshBatch();
}
void SignalImportDialog::refreshSummary(bool doPreview){
    SampleFormat f;if(current_<controller_.rows().size())f=controller_.rows()[current_].metadata.sampleFormat;
    const bool real=f.structure==SampleStructure::Real;orderField_->setVisible(bytesPerComponent(f)>1);layoutField_->setVisible(!real);normalize_->setEnabled(f.componentEncoding<ComponentEncoding::Float32);normalize_->setToolTip(normalize_->isEnabled()?"整数幅度按 ADC 满刻度缩放；磁盘不修改":"浮点保留原值，不采用整数归一化");fsLabel_->setText(real?"实采样率":"复采样率");fcLabel_->setText(real?"频率参考元数据":"RF 中心频率");
    formatCode_->setText(QString::fromStdString(formatId(f)));summary_->setText(QString("%1 · %2 · %3").arg(real?"实数 ADC":"复数 IQ",f.byteOrder==ByteOrder::NotApplicable?"字节序无关":f.byteOrder==ByteOrder::Big?"Big Endian":"Little Endian",real?"单分量实数":f.iqLayout==IQLayout::IQInterleaved?"IQ 交替":f.iqLayout==IQLayout::QIInterleaved?"QI 交替":"I/Q 分量分块"));formatSize_->setText(QString("每通道每时刻 %1 字节 · %2 个分量     磁盘每帧 %3 字节（%4 通道）").arg(bytesPerChannelSample(f)).arg(real?1:2).arg(bytesPerFrame(f)).arg(f.channels));
    if(!import_)return;if(current_>=controller_.rows().size()){import_->setEnabled(false);return;}
    auto& row=controller_.rows()[current_];QString error;FileMetadata m;
    const bool valid=row.metadataError.isEmpty()&&describeRawFile(QString::fromStdString(row.metadata.path),f,fs_->value(),fc_->value(),bw_->value(),m,error);if(!row.metadataError.isEmpty())error=row.metadataError;
    row.error=error;import_->setEnabled(valid&&row.confirmed);validation_->setText(!error.isEmpty()?error:row.confirmed?"格式参数通过基础校验 · "+row.provenance:"请确认采样结构与编码；未识别的参数不会自动按 CI16 导入");
    if(valid){countStat_->setText(QString::number(m.sampleCount));durationStat_->setText(formatAdaptiveValue(static_cast<double>(m.sampleCount)/m.sampleRateHz,UnitKind::Time));frequencyStat_->setText(formatAdaptiveValue(fullRange(m).frequency.lowerHz,UnitKind::Frequency)+" ～ "+formatAdaptiveValue(fullRange(m).frequency.upperHz,UnitKind::Frequency));row.metadata.sampleCount=m.sampleCount;row.metadata.effectiveBandwidthHz=m.effectiveBandwidthHz;stats_->setText(QString("%1 样本/通道　 ·　 %2 s<br>%3 ～ %4%5").arg(m.sampleCount).arg(static_cast<double>(m.sampleCount)/m.sampleRateHz,0,'g',7).arg(formatAdaptiveValue(fullRange(m).frequency.lowerHz,UnitKind::Frequency),formatAdaptiveValue(fullRange(m).frequency.upperHz,UnitKind::Frequency),real?"（实数）":""));footer_->setText(QString("%1 · %2 样本/通道 · %3").arg(QString::fromStdString(formatId(f))).arg(m.sampleCount).arg(row.confirmed?"参数已确认":"需确认"));
        if(doPreview){const long double begin=static_cast<long double>(start_->value())*m.sampleRateHz;const auto start=static_cast<SampleIndex>(std::min<long double>(m.sampleCount-1,begin));preview_->preview(std::move(m),std::min(m.sampleCount-1,previewSample_.value_or(start)));}}
    else {stats_->setText("— 样本　　— 时长　　— 频段");footer_->setText(error);if(doPreview)preview_->clear();}
}
void SignalImportDialog::setPage(int index){pages_->setCurrentIndex(index);if(auto* foot=findChild<QWidget*>("importFooter"))foot->setVisible(index==0);for(int i=0;i<tabs_.size();++i)tabs_[i]->setChecked(i==index);if(table_)refreshBatch();if(import_)import_->setText(index==1?"开始批量导入 →":"导入到工程 →");}
void SignalImportDialog::refreshBatch(){if(!table_)return;QString key;for(const auto& r:controller_.rows())key+=QString::fromStdString(r.metadata.path)+QString::fromStdString(sampleFormatKey(r.metadata.sampleFormat))+QString::number(r.metadata.sampleRateHz,'g',17)+statusText(r)+r.provenance+(controller_.running()?"running":"idle");
    if(current_<controller_.rows().size()){const auto& r=controller_.rows()[current_];batchSelected_->setText(QString::fromStdString(r.metadata.name)+"\n"+r.provenance+"\n"+statusText(r));}
    if(key==batchKey_)return;batchKey_=key;
    QList<int> selection;for(const auto* item:table_->selectedItems())if(!selection.contains(item->row()))selection.append(item->row());const QSignalBlocker blocker(table_);table_->setRowCount(static_cast<int>(controller_.rows().size()));for(int i=0;i<table_->rowCount();++i){const auto& row=controller_.rows()[i];const auto& m=row.metadata;const auto& f=m.sampleFormat;const QStringList values{QString::fromStdString(m.name),bytesText(static_cast<std::uint64_t>(std::max<qint64>(0,QFileInfo(QString::fromStdString(m.path)).size()))),QString::fromStdString(formatId(f))+QString(" · %1 · %2").arg(f.structure==SampleStructure::Real?"REAL":f.iqLayout==IQLayout::QIInterleaved?"QI":f.iqLayout==IQLayout::PlanarIQ?"I/Q 分块":"IQ",f.byteOrder==ByteOrder::Big?"BE":f.byteOrder==ByteOrder::Little?"LE":"NA"),formatAdaptiveValue(m.sampleRateHz,UnitKind::SampleRate),statusText(row)};for(int c=0;c<5;++c){auto* item=new QTableWidgetItem(values[c]);item->setToolTip(c==4?row.error+"\n"+row.provenance:values[c]);table_->setItem(i,c,item);if(selection.contains(i))item->setSelected(true);}auto* remove=button("×","batchRemove");remove->setToolTip("移除该文件");remove->setEnabled(!controller_.running());table_->setCellWidget(i,5,remove);connect(remove,&QPushButton::clicked,this,[this,i]{if(controller_.running())return;controller_.rows().erase(controller_.rows().begin()+i);current_=controller_.rows().empty()?0:std::min(current_,controller_.rows().size()-1);loadCurrent();refreshBatch();});}
    tabs_[1]->setText(QString("批量导入 (%1)").arg(table_->rowCount()));if(current_<controller_.rows().size()){const auto& row=controller_.rows()[current_];batchSelected_->setText(QString::fromStdString(row.metadata.name)+"\n"+row.provenance+"\n"+statusText(row));}
}
void SignalImportDialog::applyTemplate(int index,bool batch){
    if(index<0||static_cast<std::size_t>(index)>=templates_.templates().size())return;
    const auto selected=templates_.templates()[index];const auto f=selected.format;
    if(controller_.running())return;std::vector<std::size_t> rows;if(batch){for(auto* item:table_->selectedItems())if(std::find(rows.begin(),rows.end(),static_cast<std::size_t>(item->row()))==rows.end())rows.push_back(item->row());if(rows.empty())for(std::size_t i=0;i<controller_.rows().size();++i)rows.push_back(i);}else rows.push_back(current_);
    for(auto i:rows)if(i<controller_.rows().size()){
        auto& row=controller_.rows()[i];
        if((row.provenance.contains("SigMF")||row.provenance.contains("已手动覆盖"))&&row.metadata.sampleFormat!=f){
            if(QMessageBox::question(this,"确认格式覆盖",QString::fromStdString(row.metadata.name)+"：模板与现有明确格式不同，覆盖结构与编码？")!=QMessageBox::Yes)continue;
        }
        row.metadata.sampleFormat=f;row.confirmed=row.acquisitionKnown||row.confirmed;row.status=ImportStatus::Pending;
        row.provenance+=" · 用户选定模板："+selected.name+"（Fs/Fc保留）";
    }
    templates_.used(selected.id);loadCurrent();refreshBatch();refreshTemplates();
}
void SignalImportDialog::buildOverlay(){overlay_=new QWidget(this);overlay_->setObjectName("importProgressOverlay");overlay_->setStyleSheet("QWidget#importProgressOverlay{background:rgba(7,19,33,218);}");auto* outside=new QVBoxLayout(overlay_);outside->setContentsMargins(20,20,20,20);outside->addStretch();auto* center=new QHBoxLayout;center->addStretch();auto* card=new QWidget;card->setObjectName("importProgressCard");card->setFixedWidth(525);card->setStyleSheet("QWidget#importProgressCard{background:#162b41;border:1px solid #47667e;border-radius:12px;} QLabel{background:transparent;border:0;color:#8fb0c6;font-size:12px;} QProgressBar{background:#0b1b2a;border:1px solid #31506a;border-radius:4px;} QProgressBar::chunk{background:qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #187caa,stop:1 #55d3e8);border-radius:4px;}");auto* v=new QVBoxLayout(card);v->setContentsMargins(30,27,30,27);v->setSpacing(12);progressTitle_=text("正在建立信号数据源");progressTitle_->setObjectName("importProgressTitle");progressTitle_->setStyleSheet("font-size:18px;font-weight:600;color:#e0f1fa;");v->addWidget(progressTitle_);progressDescription_=text("只读验证并顺序解码真实文件，保留完整采样帧。");v->addWidget(progressDescription_);for(const auto& stage:QStringList{"验证格式与物理文件","顺序读取并建立导航包络","初始化分析数据源与首屏视图"}){auto* stageRow=new QWidget;auto* stageLayout=new QHBoxLayout(stageRow);stageLayout->setContentsMargins(0,6,0,6);stageLayout->setSpacing(10);auto* indicator=text(QString::number(stages_.size()+1));indicator->setFixedSize(23,23);indicator->setAlignment(Qt::AlignCenter);stageIndicators_.append(indicator);stageLayout->addWidget(indicator);auto* label=text(stage);label->setStyleSheet("color:#a9c9da;");stages_.append(label);stageLayout->addWidget(label,1);v->addWidget(stageRow);}progress_=new QProgressBar;progress_->setObjectName("importProgress");progress_->setRange(0,1000);progress_->setTextVisible(false);progress_->setFixedHeight(9);v->addWidget(progress_);progressMetrics_=text("0 B / 0 B · 0% · 0 样本");progressMetrics_->setObjectName("importProgressMetrics");v->addWidget(progressMetrics_);auto* buttons=new QHBoxLayout;buttons->addStretch();stop_=button("停止，保留已读前缀","importProgressStop");finish_=button("完成并进入工程","importProgressFinish");finish_->setProperty("primary",true);restart_=button("重新完整读入","importProgressRestart");buttons->addWidget(stop_);buttons->addWidget(finish_);buttons->addWidget(restart_);v->addLayout(buttons);center->addWidget(card);center->addStretch();outside->addLayout(center);outside->addStretch();overlay_->hide();
    connect(stop_,&QPushButton::clicked,this,[this]{controller_.stopAll();});connect(restart_,&QPushButton::clicked,this,[this]{controller_.restart();previewAfterLoad_=false;updateProgress();});connect(finish_,&QPushButton::clicked,this,[this]{if(!controller_.canCommit())return;for(auto file:controller_.sources()){QString error;const auto metadata=file.metadata;if(commitSource&&!commitSource(std::move(file),error)){progressDescription_->setText(error);return;}controller_.markCommitted(metadata);}accept();});
}
void SignalImportDialog::startImport(){commitConfiguration();std::vector<std::size_t> indices;if(pages_->currentIndex()==1){for(const auto* item:table_->selectedItems())if(std::find(indices.begin(),indices.end(),static_cast<std::size_t>(item->row()))==indices.end())indices.push_back(item->row());if(indices.empty())for(std::size_t i=0;i<controller_.rows().size();++i)indices.push_back(i);}else indices.push_back(current_);controller_.start(indices);previewAfterLoad_=false;overlay_->setGeometry(rect());overlay_->show();overlay_->raise();updateProgress();}
void SignalImportDialog::pollImport(){if(!overlay_->isVisible())return;controller_.poll();updateProgress();}
void SignalImportDialog::updateProgress(){if(!overlay_||!overlay_->isVisible())return;
    std::uint64_t total=0,loaded=0,bytes=0,targetBytes=0;bool partial=false;QString errors;
    for(const auto& row:controller_.rows()){if(row.load.target){total+=row.load.target;loaded+=row.load.loaded;const auto unit=row.metadata.sampleFormat.channelLayout==ChannelLayout::ChannelPlanar?bytesPerChannelSample(row.metadata.sampleFormat):bytesPerFrame(row.metadata.sampleFormat);bytes+=row.load.loaded*unit;targetBytes+=row.load.target*unit;}partial|=row.status==ImportStatus::Partial;if(!row.error.isEmpty())errors+=QString::fromStdString(row.metadata.name)+"："+row.error+"\n";}
    progress_->setValue(total?static_cast<int>(1000.L*loaded/total):0);progressMetrics_->setText(QString("%1 / %2 · %3% · %4 / %5 样本帧").arg(bytesText(bytes),bytesText(targetBytes)).arg(total?static_cast<int>(100.L*loaded/total):0).arg(loaded).arg(total));
    const bool running=controller_.running();stop_->setVisible(running);restart_->setVisible(!running&&(partial||!controller_.canCommit()));finish_->setVisible(!running);finish_->setEnabled(controller_.canCommit()&&previewAfterLoad_&&preview_->ready());
    const bool complete[]{total>0,!running&&loaded>0,!running&&preview_->ready()};for(int i=0;i<3;++i){stageIndicators_[i]->setText(complete[i]?"✓":QString::number(i+1));stageIndicators_[i]->setStyleSheet(complete[i]?"background:#1b655c;color:#85f0d0;border-radius:11px;":"background:#2d516a;color:#a9c9da;border-radius:11px;");}
    if(running){progressTitle_->setText(controller_.rows().size()>1?QString("正在导入 %1 个数据文件").arg(controller_.rows().size()):"正在建立信号数据源");return;}
    if(!previewAfterLoad_&&controller_.canCommit()){previewAfterLoad_=true;const auto sources=controller_.sources();preview_->preview(sources.front().metadata);}
    progressTitle_->setText(partial?"读入已停止 · 已保留样本前缀":controller_.canCommit()?"数据源已就绪":"没有可用数据源");progressDescription_->setText(!errors.isEmpty()?errors:partial?"完成的读取块已保留，超出可用前缀的数据不参与后续分析。":"顺序读入状态完成，已准备首屏预览及工程元数据。");finish_->setText(partial?"保留前缀并进入工程":"完成并进入工程");refreshBatch();
}
void SignalImportDialog::resizeEvent(QResizeEvent* event){QDialog::resizeEvent(event);if(overlay_)overlay_->setGeometry(rect());}
void SignalImportDialog::mousePressEvent(QMouseEvent* event){if(event->button()==Qt::LeftButton&&event->position().y()<73&&windowHandle()){windowHandle()->startSystemMove();event->accept();return;}QDialog::mousePressEvent(event);}
void SignalImportDialog::reject(){controller_.stopAll();QDialog::reject();}
void SignalImportDialog::dragEnterEvent(QDragEnterEvent* event){if(event->mimeData()->hasUrls()&&!controller_.running())event->acceptProposedAction();}
void SignalImportDialog::dropEvent(QDropEvent* event){for(const auto& url:event->mimeData()->urls())if(url.isLocalFile())addPath(url.toLocalFile());event->acceptProposedAction();}
}
